import "./config/env.js";
import express from "express";
import cors from "cors";
import passport from "passport";
import "./config/passport.js";
import authRoutes from "./routes/auth.js";
import submissionRoutes from "./routes/submissionRoutes.js";
import userRoutes from "./routes/userRoutes.js";
import activityRoutes from "./routes/activityRoutes.js";
import contestRoutes from "./routes/contestRoutes.js";
import problemRoutes from "./routes/problemRoutes.js";
import courseRoutes from "./routes/courseRoutes.js"
import progressRoutes from "./routes/progressRoutes.js";
import codeExecutionRoutes from "./routes/codeExecutionRoutes.js";
import "./config/db.js";
const app = express();
app.use(cors());
app.use(express.json());
app.use(passport.initialize());
app.use("/api/auth", authRoutes);
app.use("/api/submissions", submissionRoutes);
app.use("/api/users", userRoutes);
app.use("/api/activity", activityRoutes);
app.use("/api/contest", contestRoutes);
app.use("/api/problems", problemRoutes);
app.use("/api/courses", courseRoutes);
app.use("/api/progress", progressRoutes);
app.use("/api/code", codeExecutionRoutes);
const PORT = 5000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});