import "./config/env.js";
import express from "express";
import cors from "cors";
import passport from "passport";
import "./config/passport.js";
import authRoutes from "./routes/auth.js";
import submissionRoutes from "./routes/submissionRoutes.js";
import userRoutes from "./routes/userRoutes.js";
import "./config/db.js";
const app = express();
app.use(cors());
app.use(express.json());
app.use(passport.initialize());
app.use("/api/auth", authRoutes);
app.use("/api/submissions", submissionRoutes);
app.use("/api/users", userRoutes);
const PORT = 5000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});